var util = require('util');
var sails = require('sails');
var fs = require('fs');
var inflection = require('inflection');
var utilities = require('./utilities');


module.exports.routes = function () {
    var routes = {
        'GET /': 'AdminController.index',
        'GET /admin': 'AdminController.index',
        'GET /admin/index': 'AdminController.index',
        'GET /admin/objectCounts': 'AdminController.countAll',
        'GET /health-check': 'APHealthCheckController.healthcheck',
        // Unversioned authentication routes
        'POST /auth/:strategy/callback': 'APAuthenticatedSessionsController.login',
        'PUT /auth/:strategy/callback': 'APAuthenticatedSessionsController.login',
        'GET /auth/:strategy/callback': 'APAuthenticatedSessionsController.login',
        'PATCH /auth/:strategy/callback': 'APAuthenticatedSessionsController.login',
        'DELETE /auth/:strategy/callback': 'APAuthenticatedSessionsController.login',
        
        // Versioned authentication routes
        'POST /auth/:version/:strategy/callback': 'APAuthenticatedSessionsController.login',
        'PUT /auth/:version/:strategy/callback': 'APAuthenticatedSessionsController.login',
        'GET /auth/:version/:strategy/callback': 'APAuthenticatedSessionsController.login',
        'PATCH /auth/:version/:strategy/callback': 'APAuthenticatedSessionsController.login',
        'DELETE /auth/:version/:strategy/callback': 'APAuthenticatedSessionsController.login',
        

        'POST /auth/signout': 'APAuthenticatedSessionsController.logout',
        'GET /api/activity' : 'ActivityController.find',
        'DELETE /api/activity/:id' : 'ActivityController.destroy',
        'POST /api/activity' : 'ActivityController.create',
        'PUT /api/activity' : 'ActivityController.update',
        'GET /api/activity/:id' : 'ActivityController.findById',
        'POST /api/activity/aggregate' : 'ActivityController.aggregate',
        'GET /api/info' : 'InfoController.find',

        'POST /api/push_notifications/channel/subscribe' : 'ChannelController.subscribe',
        'POST /api/push_notifications/channel/unsubscribe' : 'ChannelController.unsubscribe',
        'GET /api/push_notifications/device/:identifier/channels' : 'DeviceController.findDeviceChannels',
        'POST /api/push_notifications/message' : 'MessageController.create',

        'GET /api/push_notifications/apps' : 'AppController.find',
        'GET /api/push_notifications/apps/:id' : 'AppController.find',
        'DELETE /api/push_notifications/apps/:id' : 'AppController.destroy',
        'PUT /api/push_notifications/apps/:id' : 'AppController.update',
        'POST /api/push_notifications/apps/:id' : 'AppController.update',
        'POST /api/push_notifications/apps' : 'AppController.create',

        'GET /api/push_notifications/apps/:app_id/devices' : 'DeviceController.find',
        'GET /api/push_notifications/apps/:app_id/devices/:id' : 'DeviceController.find',
        'DELETE /api/push_notifications/apps/:app_id/devices/:id' : 'DeviceController.destroy',
        'POST /api/push_notifications/apps/:app_id/devices' : 'DeviceController.create',
        'PUT /api/push_notifications/apps/:app_id/devices' : 'DeviceController.update',
        'PUT /api/push_notifications/apps/:app_id/devices/:id' : 'DeviceController.update',
        'GET /api/push_notifications/apps/:app_id/devices/:id/channels' : 'DeviceController.findDeviceChannels',
        
        'GET /api/push_notifications/apps/:app_id/channels' : 'ChannelController.find',
        'GET /api/push_notifications/apps/:app_id/channels/:id' : 'ChannelController.find',
        'DELETE /api/push_notifications/apps/:app_id/channels' : 'ChannelController.destroy',
        'DELETE /api/push_notifications/apps/:app_id/channels/:id' : 'ChannelController.destroy',
        'POST /api/push_notifications/apps/:app_id/channels' : 'ChannelController.create',
        'PUT /api/push_notifications/apps/:app_id/channels' : 'ChannelController.update',
        'PUT /api/push_notifications/apps/:app_id/channels/:id' : 'ChannelController.update',
        'POST /api/push_notifications/apps/:app_id/channels/:id/subscribe' : 'ChannelController.subscribe',
        'POST /api/push_notifications/apps/:app_id/channels/unsubscribe' : 'ChannelController.unsubscribe',

        'GET /api/push_notifications/apps/:app_id/messages' : 'MessageController.find',
        'GET /api/push_notifications/apps/:app_id/messages/:id' : 'MessageController.find',
        'GET /api/push_notifications/channels/:channel_id/messages' : 'MessageController.findChannelMessages',

        // Begin Version 1
        
        "GET /api/v1/clinician_block_randomizers/:id?.?(json)?": "V1ClinicianBlockRandomizerController.find",
        "GET /api/v1/clinician_block_randomizers/files/:type/:id": "V1ClinicianBlockRandomizerController.file",
        "POST /api/v1/clinician_block_randomizers(.json)?": "V1ClinicianBlockRandomizerController.create",
        "PATCH /api/v1/clinician_block_randomizers/:id.?(json)?": "V1ClinicianBlockRandomizerController.update",
        "PUT /api/v1/clinician_block_randomizers/:id.?(json)?": "V1ClinicianBlockRandomizerController.update",
        "DELETE /api/v1/clinician_block_randomizers/:id.?(json)?": "V1ClinicianBlockRandomizerController.destroy",
        
        "GET /api/v1/clinician_codes/:id?.?(json)?": "V1ClinicianCodeController.find",
        "GET /api/v1/clinician_codes/files/:type/:id": "V1ClinicianCodeController.file",
        "POST /api/v1/clinician_codes(.json)?": "V1ClinicianCodeController.create",
        "PATCH /api/v1/clinician_codes/:id.?(json)?": "V1ClinicianCodeController.update",
        "PUT /api/v1/clinician_codes/:id.?(json)?": "V1ClinicianCodeController.update",
        "DELETE /api/v1/clinician_codes/:id.?(json)?": "V1ClinicianCodeController.destroy",
        
        "GET /api/v1/educations/:id?.?(json)?": "V1EducationController.find",
        "GET /api/v1/educations/files/:type/:id": "V1EducationController.file",
        "POST /api/v1/educations(.json)?": "V1EducationController.create",
        "PATCH /api/v1/educations/:id.?(json)?": "V1EducationController.update",
        "PUT /api/v1/educations/:id.?(json)?": "V1EducationController.update",
        "DELETE /api/v1/educations/:id.?(json)?": "V1EducationController.destroy",
        
        "GET /api/v1/healthcare_provider_contents/:id?.?(json)?": "V1HealthcareProviderContentController.find",
        "GET /api/v1/healthcare_provider_contents/files/:type/:id": "V1HealthcareProviderContentController.file",
        "POST /api/v1/healthcare_provider_contents(.json)?": "V1HealthcareProviderContentController.create",
        "PATCH /api/v1/healthcare_provider_contents/:id.?(json)?": "V1HealthcareProviderContentController.update",
        "PUT /api/v1/healthcare_provider_contents/:id.?(json)?": "V1HealthcareProviderContentController.update",
        "DELETE /api/v1/healthcare_provider_contents/:id.?(json)?": "V1HealthcareProviderContentController.destroy",
        
        "GET /api/v1/job_audit_loggings/:id?.?(json)?": "V1JobAuditLoggingController.find",
        "GET /api/v1/job_audit_loggings/files/:type/:id": "V1JobAuditLoggingController.file",
        "POST /api/v1/job_audit_loggings(.json)?": "V1JobAuditLoggingController.create",
        "PATCH /api/v1/job_audit_loggings/:id.?(json)?": "V1JobAuditLoggingController.update",
        "PUT /api/v1/job_audit_loggings/:id.?(json)?": "V1JobAuditLoggingController.update",
        "DELETE /api/v1/job_audit_loggings/:id.?(json)?": "V1JobAuditLoggingController.destroy",
        
        "GET /api/v1/question_categories/:id?.?(json)?": "V1QuestionCategoryController.find",
        "GET /api/v1/question_categories/files/:type/:id": "V1QuestionCategoryController.file",
        "POST /api/v1/question_categories(.json)?": "V1QuestionCategoryController.create",
        "PATCH /api/v1/question_categories/:id.?(json)?": "V1QuestionCategoryController.update",
        "PUT /api/v1/question_categories/:id.?(json)?": "V1QuestionCategoryController.update",
        "DELETE /api/v1/question_categories/:id.?(json)?": "V1QuestionCategoryController.destroy",
        
        "GET /api/v1/question_codes/:id?.?(json)?": "V1QuestionCodeController.find",
        "GET /api/v1/question_codes/files/:type/:id": "V1QuestionCodeController.file",
        "POST /api/v1/question_codes(.json)?": "V1QuestionCodeController.create",
        "PATCH /api/v1/question_codes/:id.?(json)?": "V1QuestionCodeController.update",
        "PUT /api/v1/question_codes/:id.?(json)?": "V1QuestionCodeController.update",
        "DELETE /api/v1/question_codes/:id.?(json)?": "V1QuestionCodeController.destroy",
        
        "GET /api/v1/question_types/:id?.?(json)?": "V1QuestionTypeController.find",
        "GET /api/v1/question_types/files/:type/:id": "V1QuestionTypeController.file",
        "POST /api/v1/question_types(.json)?": "V1QuestionTypeController.create",
        "PATCH /api/v1/question_types/:id.?(json)?": "V1QuestionTypeController.update",
        "PUT /api/v1/question_types/:id.?(json)?": "V1QuestionTypeController.update",
        "DELETE /api/v1/question_types/:id.?(json)?": "V1QuestionTypeController.destroy",
        
        "GET /api/v1/races/:id?.?(json)?": "V1RaceController.find",
        "GET /api/v1/races/files/:type/:id": "V1RaceController.file",
        "POST /api/v1/races(.json)?": "V1RaceController.create",
        "PATCH /api/v1/races/:id.?(json)?": "V1RaceController.update",
        "PUT /api/v1/races/:id.?(json)?": "V1RaceController.update",
        "DELETE /api/v1/races/:id.?(json)?": "V1RaceController.destroy",
        
        "GET /api/v1/search_audit_loggings/:id?.?(json)?": "V1SearchAuditLoggingController.find",
        "GET /api/v1/search_audit_loggings/files/:type/:id": "V1SearchAuditLoggingController.file",
        "POST /api/v1/search_audit_loggings(.json)?": "V1SearchAuditLoggingController.create",
        "PATCH /api/v1/search_audit_loggings/:id.?(json)?": "V1SearchAuditLoggingController.update",
        "PUT /api/v1/search_audit_loggings/:id.?(json)?": "V1SearchAuditLoggingController.update",
        "DELETE /api/v1/search_audit_loggings/:id.?(json)?": "V1SearchAuditLoggingController.destroy",
        
        "GET /api/v1/send_grids/:id?.?(json)?": "V1SendGridController.find",
        "GET /api/v1/send_grids/files/:type/:id": "V1SendGridController.file",
        "POST /api/v1/send_grids(.json)?": "V1SendGridController.create",
        "PATCH /api/v1/send_grids/:id.?(json)?": "V1SendGridController.update",
        "PUT /api/v1/send_grids/:id.?(json)?": "V1SendGridController.update",
        "DELETE /api/v1/send_grids/:id.?(json)?": "V1SendGridController.destroy",
        
        "GET /api/v1/settings/:id?.?(json)?": "V1SettingController.find",
        "GET /api/v1/settings/files/:type/:id": "V1SettingController.file",
        "POST /api/v1/settings(.json)?": "V1SettingController.create",
        "PATCH /api/v1/settings/:id.?(json)?": "V1SettingController.update",
        "PUT /api/v1/settings/:id.?(json)?": "V1SettingController.update",
        "DELETE /api/v1/settings/:id.?(json)?": "V1SettingController.destroy",
        
        "GET /api/v1/surveys/:id?.?(json)?": "V1SurveyController.find",
        "GET /api/v1/surveys/files/:type/:id": "V1SurveyController.file",
        "POST /api/v1/surveys(.json)?": "V1SurveyController.create",
        "PATCH /api/v1/surveys/:id.?(json)?": "V1SurveyController.update",
        "PUT /api/v1/surveys/:id.?(json)?": "V1SurveyController.update",
        "DELETE /api/v1/surveys/:id.?(json)?": "V1SurveyController.destroy",
        
        "GET /api/v1/survey_answers/:id?.?(json)?": "V1SurveyAnswerController.find",
        "GET /api/v1/survey_answers/files/:type/:id": "V1SurveyAnswerController.file",
        "POST /api/v1/survey_answers(.json)?": "V1SurveyAnswerController.create",
        "PATCH /api/v1/survey_answers/:id.?(json)?": "V1SurveyAnswerController.update",
        "PUT /api/v1/survey_answers/:id.?(json)?": "V1SurveyAnswerController.update",
        "DELETE /api/v1/survey_answers/:id.?(json)?": "V1SurveyAnswerController.destroy",
        
        "GET /api/v1/survey_questions/:id?.?(json)?": "V1SurveyQuestionController.find",
        "GET /api/v1/survey_questions/files/:type/:id": "V1SurveyQuestionController.file",
        "POST /api/v1/survey_questions(.json)?": "V1SurveyQuestionController.create",
        "PATCH /api/v1/survey_questions/:id.?(json)?": "V1SurveyQuestionController.update",
        "PUT /api/v1/survey_questions/:id.?(json)?": "V1SurveyQuestionController.update",
        "DELETE /api/v1/survey_questions/:id.?(json)?": "V1SurveyQuestionController.destroy",
        
        "GET /api/v1/survey_question_skip_logics/:id?.?(json)?": "V1SurveyQuestionSkipLogicController.find",
        "GET /api/v1/survey_question_skip_logics/files/:type/:id": "V1SurveyQuestionSkipLogicController.file",
        "POST /api/v1/survey_question_skip_logics(.json)?": "V1SurveyQuestionSkipLogicController.create",
        "PATCH /api/v1/survey_question_skip_logics/:id.?(json)?": "V1SurveyQuestionSkipLogicController.update",
        "PUT /api/v1/survey_question_skip_logics/:id.?(json)?": "V1SurveyQuestionSkipLogicController.update",
        "DELETE /api/v1/survey_question_skip_logics/:id.?(json)?": "V1SurveyQuestionSkipLogicController.destroy",
        
        "GET /api/v1/topics/:id?.?(json)?": "V1TopicController.find",
        "GET /api/v1/topics/files/:type/:id": "V1TopicController.file",
        "POST /api/v1/topics(.json)?": "V1TopicController.create",
        "PATCH /api/v1/topics/:id.?(json)?": "V1TopicController.update",
        "PUT /api/v1/topics/:id.?(json)?": "V1TopicController.update",
        "DELETE /api/v1/topics/:id.?(json)?": "V1TopicController.destroy",
        
        "GET /api/v1/twilios/:id?.?(json)?": "V1TwilioController.find",
        "GET /api/v1/twilios/files/:type/:id": "V1TwilioController.file",
        "POST /api/v1/twilios(.json)?": "V1TwilioController.create",
        "PATCH /api/v1/twilios/:id.?(json)?": "V1TwilioController.update",
        "PUT /api/v1/twilios/:id.?(json)?": "V1TwilioController.update",
        "DELETE /api/v1/twilios/:id.?(json)?": "V1TwilioController.destroy",
        
        "GET /api/v1/users/:id?.?(json)?": "V1UserController.find",
        "GET /api/v1/users/files/:type/:id": "V1UserController.file",
        "POST /api/v1/users(.json)?": "V1UserController.create",
        "PATCH /api/v1/users/:id.?(json)?": "V1UserController.update",
        "PUT /api/v1/users/:id.?(json)?": "V1UserController.update",
        "DELETE /api/v1/users/:id.?(json)?": "V1UserController.destroy",
        
        "GET /api/v1/user_audit_loggings/:id?.?(json)?": "V1UserAuditLoggingController.find",
        "GET /api/v1/user_audit_loggings/files/:type/:id": "V1UserAuditLoggingController.file",
        "POST /api/v1/user_audit_loggings(.json)?": "V1UserAuditLoggingController.create",
        "PATCH /api/v1/user_audit_loggings/:id.?(json)?": "V1UserAuditLoggingController.update",
        "PUT /api/v1/user_audit_loggings/:id.?(json)?": "V1UserAuditLoggingController.update",
        "DELETE /api/v1/user_audit_loggings/:id.?(json)?": "V1UserAuditLoggingController.destroy",
        
        "GET /api/v1/user_surveys/:id?.?(json)?": "V1UserSurveyController.find",
        "GET /api/v1/user_surveys/files/:type/:id": "V1UserSurveyController.file",
        "POST /api/v1/user_surveys(.json)?": "V1UserSurveyController.create",
        "PATCH /api/v1/user_surveys/:id.?(json)?": "V1UserSurveyController.update",
        "PUT /api/v1/user_surveys/:id.?(json)?": "V1UserSurveyController.update",
        "DELETE /api/v1/user_surveys/:id.?(json)?": "V1UserSurveyController.destroy",
        
        "GET /api/v1/user_survey_answers/:id?.?(json)?": "V1UserSurveyAnswerController.find",
        "GET /api/v1/user_survey_answers/files/:type/:id": "V1UserSurveyAnswerController.file",
        "POST /api/v1/user_survey_answers(.json)?": "V1UserSurveyAnswerController.create",
        "PATCH /api/v1/user_survey_answers/:id.?(json)?": "V1UserSurveyAnswerController.update",
        "PUT /api/v1/user_survey_answers/:id.?(json)?": "V1UserSurveyAnswerController.update",
        "DELETE /api/v1/user_survey_answers/:id.?(json)?": "V1UserSurveyAnswerController.destroy",
        
        "GET /api/v1/vaccination_reminders/:id?.?(json)?": "V1VaccinationReminderController.find",
        "GET /api/v1/vaccination_reminders/files/:type/:id": "V1VaccinationReminderController.file",
        "POST /api/v1/vaccination_reminders(.json)?": "V1VaccinationReminderController.create",
        "PATCH /api/v1/vaccination_reminders/:id.?(json)?": "V1VaccinationReminderController.update",
        "PUT /api/v1/vaccination_reminders/:id.?(json)?": "V1VaccinationReminderController.update",
        "DELETE /api/v1/vaccination_reminders/:id.?(json)?": "V1VaccinationReminderController.destroy",
        
        "GET /api/v1/videos/:id?.?(json)?": "V1VideoController.find",
        "GET /api/v1/videos/files/:type/:id": "V1VideoController.file",
        "POST /api/v1/videos(.json)?": "V1VideoController.create",
        "PATCH /api/v1/videos/:id.?(json)?": "V1VideoController.update",
        "PUT /api/v1/videos/:id.?(json)?": "V1VideoController.update",
        "DELETE /api/v1/videos/:id.?(json)?": "V1VideoController.destroy",
        
        "GET /api/v1/video_audit_loggings/:id?.?(json)?": "V1VideoAuditLoggingController.find",
        "GET /api/v1/video_audit_loggings/files/:type/:id": "V1VideoAuditLoggingController.file",
        "POST /api/v1/video_audit_loggings(.json)?": "V1VideoAuditLoggingController.create",
        "PATCH /api/v1/video_audit_loggings/:id.?(json)?": "V1VideoAuditLoggingController.update",
        "PUT /api/v1/video_audit_loggings/:id.?(json)?": "V1VideoAuditLoggingController.update",
        "DELETE /api/v1/video_audit_loggings/:id.?(json)?": "V1VideoAuditLoggingController.destroy",
        

        // Non RESTful API routes
        'POST /api/v1/push_notifications/push_notifications/channel/subscribe' : 'ChannelController.subscribe',
        'POST /api/v1/push_notifications/push_notifications/channel/unsubscribe' : 'ChannelController.unsubscribe',
        'GET /api/v1/push_notifications/device/:identifier/channels' : 'DeviceController.findDeviceChannels',

        // RESTful API routes, mostly used by the admin UI
        'GET /api/v1/push_notifications/apps' : 'AppController.find',
        'GET /api/v1/push_notifications/apps/:id' : 'AppController.find',
        'DELETE /api/v1/push_notifications/apps/:id' : 'AppController.destroy',
        'PUT /api/v1/push_notifications/apps/:id' : 'AppController.update',
        'POST /api/v1/push_notifications/apps/:id' : 'AppController.update',
        'POST /api/v1/push_notifications/apps' : 'AppController.create',

        'GET /api/v1/push_notifications/apps/:app_id/devices' : 'DeviceController.find',
        'GET /api/v1/push_notifications/apps/:app_id/devices/:id' : 'DeviceController.find',
        'DELETE /api/v1/push_notifications/apps/:app_id/devices/:id' : 'DeviceController.destroy',
        'POST /api/v1/push_notifications/apps/:app_id/devices' : 'DeviceController.create',
        'PUT /api/v1/push_notifications/apps/:app_id/devices' : 'DeviceController.update',
        'PUT /api/v1/push_notifications/apps/:app_id/devices/:id' : 'DeviceController.update',
        'GET /api/v1/push_notifications/apps/:app_id/devices/:id/channels' : 'DeviceController.findDeviceChannels',

        'GET /api/v1/push_notifications/apps/:app_id/channels' : 'ChannelController.find',
        'GET /api/v1/push_notifications/apps/:app_id/channels/:id' : 'ChannelController.find',
        'DELETE /api/v1/push_notifications/apps/:app_id/channels' : 'ChannelController.destroy',
        'DELETE /api/v1/push_notifications/apps/:app_id/channels/:id' : 'ChannelController.destroy',
        'POST /api/v1/push_notifications/apps/:app_id/channels' : 'ChannelController.create',
        'PUT /api/v1/push_notifications/apps/:app_id/channels' : 'ChannelController.update',
        'PUT /api/v1/push_notifications/apps/:app_id/channels/:id' : 'ChannelController.update',
        'POST /api/v1/push_notifications/apps/:app_id/channels/:id/subscribe' : 'ChannelController.subscribe',
        'POST /api/v1/push_notifications/apps/:app_id/channels/unsubscribe' : 'ChannelController.unsubscribe',

        'GET /api/v1/push_notifications/apps/:app_id/messages' : 'MessageController.find',
        'GET /api/v1/push_notifications/apps/:app_id/messages/:id' : 'MessageController.find',
        'GET /api/v1/push_notifications/channels/:channel_id/messages' : 'MessageController.findChannelMessages',
        // End Version 1

        // Begin Version 2
        
        "GET /api/v2/clinician_block_randomizers/:id?.?(json)?": "V2ClinicianBlockRandomizerController.find",
        "GET /api/v2/clinician_block_randomizers/files/:type/:id": "V2ClinicianBlockRandomizerController.file",
        "POST /api/v2/clinician_block_randomizers(.json)?": "V2ClinicianBlockRandomizerController.create",
        "PATCH /api/v2/clinician_block_randomizers/:id.?(json)?": "V2ClinicianBlockRandomizerController.update",
        "PUT /api/v2/clinician_block_randomizers/:id.?(json)?": "V2ClinicianBlockRandomizerController.update",
        "DELETE /api/v2/clinician_block_randomizers/:id.?(json)?": "V2ClinicianBlockRandomizerController.destroy",
        
        "GET /api/v2/clinician_codes/:id?.?(json)?": "V2ClinicianCodeController.find",
        "GET /api/v2/clinician_codes/files/:type/:id": "V2ClinicianCodeController.file",
        "POST /api/v2/clinician_codes(.json)?": "V2ClinicianCodeController.create",
        "PATCH /api/v2/clinician_codes/:id.?(json)?": "V2ClinicianCodeController.update",
        "PUT /api/v2/clinician_codes/:id.?(json)?": "V2ClinicianCodeController.update",
        "DELETE /api/v2/clinician_codes/:id.?(json)?": "V2ClinicianCodeController.destroy",
        
        "GET /api/v2/educations/:id?.?(json)?": "V2EducationController.find",
        "GET /api/v2/educations/files/:type/:id": "V2EducationController.file",
        "POST /api/v2/educations(.json)?": "V2EducationController.create",
        "PATCH /api/v2/educations/:id.?(json)?": "V2EducationController.update",
        "PUT /api/v2/educations/:id.?(json)?": "V2EducationController.update",
        "DELETE /api/v2/educations/:id.?(json)?": "V2EducationController.destroy",
        
        "GET /api/v2/healthcare_provider_contents/:id?.?(json)?": "V2HealthcareProviderContentController.find",
        "GET /api/v2/healthcare_provider_contents/files/:type/:id": "V2HealthcareProviderContentController.file",
        "POST /api/v2/healthcare_provider_contents(.json)?": "V2HealthcareProviderContentController.create",
        "PATCH /api/v2/healthcare_provider_contents/:id.?(json)?": "V2HealthcareProviderContentController.update",
        "PUT /api/v2/healthcare_provider_contents/:id.?(json)?": "V2HealthcareProviderContentController.update",
        "DELETE /api/v2/healthcare_provider_contents/:id.?(json)?": "V2HealthcareProviderContentController.destroy",
        
        "GET /api/v2/job_audit_loggings/:id?.?(json)?": "V2JobAuditLoggingController.find",
        "GET /api/v2/job_audit_loggings/files/:type/:id": "V2JobAuditLoggingController.file",
        "POST /api/v2/job_audit_loggings(.json)?": "V2JobAuditLoggingController.create",
        "PATCH /api/v2/job_audit_loggings/:id.?(json)?": "V2JobAuditLoggingController.update",
        "PUT /api/v2/job_audit_loggings/:id.?(json)?": "V2JobAuditLoggingController.update",
        "DELETE /api/v2/job_audit_loggings/:id.?(json)?": "V2JobAuditLoggingController.destroy",
        
        "GET /api/v2/question_categories/:id?.?(json)?": "V2QuestionCategoryController.find",
        "GET /api/v2/question_categories/files/:type/:id": "V2QuestionCategoryController.file",
        "POST /api/v2/question_categories(.json)?": "V2QuestionCategoryController.create",
        "PATCH /api/v2/question_categories/:id.?(json)?": "V2QuestionCategoryController.update",
        "PUT /api/v2/question_categories/:id.?(json)?": "V2QuestionCategoryController.update",
        "DELETE /api/v2/question_categories/:id.?(json)?": "V2QuestionCategoryController.destroy",
        
        "GET /api/v2/question_codes/:id?.?(json)?": "V2QuestionCodeController.find",
        "GET /api/v2/question_codes/files/:type/:id": "V2QuestionCodeController.file",
        "POST /api/v2/question_codes(.json)?": "V2QuestionCodeController.create",
        "PATCH /api/v2/question_codes/:id.?(json)?": "V2QuestionCodeController.update",
        "PUT /api/v2/question_codes/:id.?(json)?": "V2QuestionCodeController.update",
        "DELETE /api/v2/question_codes/:id.?(json)?": "V2QuestionCodeController.destroy",
        
        "GET /api/v2/question_types/:id?.?(json)?": "V2QuestionTypeController.find",
        "GET /api/v2/question_types/files/:type/:id": "V2QuestionTypeController.file",
        "POST /api/v2/question_types(.json)?": "V2QuestionTypeController.create",
        "PATCH /api/v2/question_types/:id.?(json)?": "V2QuestionTypeController.update",
        "PUT /api/v2/question_types/:id.?(json)?": "V2QuestionTypeController.update",
        "DELETE /api/v2/question_types/:id.?(json)?": "V2QuestionTypeController.destroy",
        
        "GET /api/v2/races/:id?.?(json)?": "V2RaceController.find",
        "GET /api/v2/races/files/:type/:id": "V2RaceController.file",
        "POST /api/v2/races(.json)?": "V2RaceController.create",
        "PATCH /api/v2/races/:id.?(json)?": "V2RaceController.update",
        "PUT /api/v2/races/:id.?(json)?": "V2RaceController.update",
        "DELETE /api/v2/races/:id.?(json)?": "V2RaceController.destroy",
        
        "GET /api/v2/search_audit_loggings/:id?.?(json)?": "V2SearchAuditLoggingController.find",
        "GET /api/v2/search_audit_loggings/files/:type/:id": "V2SearchAuditLoggingController.file",
        "POST /api/v2/search_audit_loggings(.json)?": "V2SearchAuditLoggingController.create",
        "PATCH /api/v2/search_audit_loggings/:id.?(json)?": "V2SearchAuditLoggingController.update",
        "PUT /api/v2/search_audit_loggings/:id.?(json)?": "V2SearchAuditLoggingController.update",
        "DELETE /api/v2/search_audit_loggings/:id.?(json)?": "V2SearchAuditLoggingController.destroy",
        
        "GET /api/v2/send_grids/:id?.?(json)?": "V2SendGridController.find",
        "GET /api/v2/send_grids/files/:type/:id": "V2SendGridController.file",
        "POST /api/v2/send_grids(.json)?": "V2SendGridController.create",
        "PATCH /api/v2/send_grids/:id.?(json)?": "V2SendGridController.update",
        "PUT /api/v2/send_grids/:id.?(json)?": "V2SendGridController.update",
        "DELETE /api/v2/send_grids/:id.?(json)?": "V2SendGridController.destroy",
        
        "GET /api/v2/settings/:id?.?(json)?": "V2SettingController.find",
        "GET /api/v2/settings/files/:type/:id": "V2SettingController.file",
        "POST /api/v2/settings(.json)?": "V2SettingController.create",
        "PATCH /api/v2/settings/:id.?(json)?": "V2SettingController.update",
        "PUT /api/v2/settings/:id.?(json)?": "V2SettingController.update",
        "DELETE /api/v2/settings/:id.?(json)?": "V2SettingController.destroy",
        
        "GET /api/v2/surveys/:id?.?(json)?": "V2SurveyController.find",
        "GET /api/v2/surveys/files/:type/:id": "V2SurveyController.file",
        "POST /api/v2/surveys(.json)?": "V2SurveyController.create",
        "PATCH /api/v2/surveys/:id.?(json)?": "V2SurveyController.update",
        "PUT /api/v2/surveys/:id.?(json)?": "V2SurveyController.update",
        "DELETE /api/v2/surveys/:id.?(json)?": "V2SurveyController.destroy",
        
        "GET /api/v2/survey_answers/:id?.?(json)?": "V2SurveyAnswerController.find",
        "GET /api/v2/survey_answers/files/:type/:id": "V2SurveyAnswerController.file",
        "POST /api/v2/survey_answers(.json)?": "V2SurveyAnswerController.create",
        "PATCH /api/v2/survey_answers/:id.?(json)?": "V2SurveyAnswerController.update",
        "PUT /api/v2/survey_answers/:id.?(json)?": "V2SurveyAnswerController.update",
        "DELETE /api/v2/survey_answers/:id.?(json)?": "V2SurveyAnswerController.destroy",
        
        "GET /api/v2/survey_questions/:id?.?(json)?": "V2SurveyQuestionController.find",
        "GET /api/v2/survey_questions/files/:type/:id": "V2SurveyQuestionController.file",
        "POST /api/v2/survey_questions(.json)?": "V2SurveyQuestionController.create",
        "PATCH /api/v2/survey_questions/:id.?(json)?": "V2SurveyQuestionController.update",
        "PUT /api/v2/survey_questions/:id.?(json)?": "V2SurveyQuestionController.update",
        "DELETE /api/v2/survey_questions/:id.?(json)?": "V2SurveyQuestionController.destroy",
        
        "GET /api/v2/survey_question_skip_logics/:id?.?(json)?": "V2SurveyQuestionSkipLogicController.find",
        "GET /api/v2/survey_question_skip_logics/files/:type/:id": "V2SurveyQuestionSkipLogicController.file",
        "POST /api/v2/survey_question_skip_logics(.json)?": "V2SurveyQuestionSkipLogicController.create",
        "PATCH /api/v2/survey_question_skip_logics/:id.?(json)?": "V2SurveyQuestionSkipLogicController.update",
        "PUT /api/v2/survey_question_skip_logics/:id.?(json)?": "V2SurveyQuestionSkipLogicController.update",
        "DELETE /api/v2/survey_question_skip_logics/:id.?(json)?": "V2SurveyQuestionSkipLogicController.destroy",
        
        "GET /api/v2/topics/:id?.?(json)?": "V2TopicController.find",
        "GET /api/v2/topics/files/:type/:id": "V2TopicController.file",
        "POST /api/v2/topics(.json)?": "V2TopicController.create",
        "PATCH /api/v2/topics/:id.?(json)?": "V2TopicController.update",
        "PUT /api/v2/topics/:id.?(json)?": "V2TopicController.update",
        "DELETE /api/v2/topics/:id.?(json)?": "V2TopicController.destroy",
        
        "GET /api/v2/twilios/:id?.?(json)?": "V2TwilioController.find",
        "GET /api/v2/twilios/files/:type/:id": "V2TwilioController.file",
        "POST /api/v2/twilios(.json)?": "V2TwilioController.create",
        "PATCH /api/v2/twilios/:id.?(json)?": "V2TwilioController.update",
        "PUT /api/v2/twilios/:id.?(json)?": "V2TwilioController.update",
        "DELETE /api/v2/twilios/:id.?(json)?": "V2TwilioController.destroy",
        
        "GET /api/v2/users/:id?.?(json)?": "V2UserController.find",
        "GET /api/v2/users/files/:type/:id": "V2UserController.file",
        "POST /api/v2/users(.json)?": "V2UserController.create",
        "PATCH /api/v2/users/:id.?(json)?": "V2UserController.update",
        "PUT /api/v2/users/:id.?(json)?": "V2UserController.update",
        "DELETE /api/v2/users/:id.?(json)?": "V2UserController.destroy",
        
        "GET /api/v2/user_audit_loggings/:id?.?(json)?": "V2UserAuditLoggingController.find",
        "GET /api/v2/user_audit_loggings/files/:type/:id": "V2UserAuditLoggingController.file",
        "POST /api/v2/user_audit_loggings(.json)?": "V2UserAuditLoggingController.create",
        "PATCH /api/v2/user_audit_loggings/:id.?(json)?": "V2UserAuditLoggingController.update",
        "PUT /api/v2/user_audit_loggings/:id.?(json)?": "V2UserAuditLoggingController.update",
        "DELETE /api/v2/user_audit_loggings/:id.?(json)?": "V2UserAuditLoggingController.destroy",
        
        "GET /api/v2/user_surveys/:id?.?(json)?": "V2UserSurveyController.find",
        "GET /api/v2/user_surveys/files/:type/:id": "V2UserSurveyController.file",
        "POST /api/v2/user_surveys(.json)?": "V2UserSurveyController.create",
        "PATCH /api/v2/user_surveys/:id.?(json)?": "V2UserSurveyController.update",
        "PUT /api/v2/user_surveys/:id.?(json)?": "V2UserSurveyController.update",
        "DELETE /api/v2/user_surveys/:id.?(json)?": "V2UserSurveyController.destroy",
        
        "GET /api/v2/user_survey_answers/:id?.?(json)?": "V2UserSurveyAnswerController.find",
        "GET /api/v2/user_survey_answers/files/:type/:id": "V2UserSurveyAnswerController.file",
        "POST /api/v2/user_survey_answers(.json)?": "V2UserSurveyAnswerController.create",
        "PATCH /api/v2/user_survey_answers/:id.?(json)?": "V2UserSurveyAnswerController.update",
        "PUT /api/v2/user_survey_answers/:id.?(json)?": "V2UserSurveyAnswerController.update",
        "DELETE /api/v2/user_survey_answers/:id.?(json)?": "V2UserSurveyAnswerController.destroy",
        
        "GET /api/v2/user_survey_videos/:id?.?(json)?": "V2UserSurveyVideoController.find",
        "GET /api/v2/user_survey_videos/files/:type/:id": "V2UserSurveyVideoController.file",
        "POST /api/v2/user_survey_videos(.json)?": "V2UserSurveyVideoController.create",
        "PATCH /api/v2/user_survey_videos/:id.?(json)?": "V2UserSurveyVideoController.update",
        "PUT /api/v2/user_survey_videos/:id.?(json)?": "V2UserSurveyVideoController.update",
        "DELETE /api/v2/user_survey_videos/:id.?(json)?": "V2UserSurveyVideoController.destroy",
        
        "GET /api/v2/vaccination_reminders/:id?.?(json)?": "V2VaccinationReminderController.find",
        "GET /api/v2/vaccination_reminders/files/:type/:id": "V2VaccinationReminderController.file",
        "POST /api/v2/vaccination_reminders(.json)?": "V2VaccinationReminderController.create",
        "PATCH /api/v2/vaccination_reminders/:id.?(json)?": "V2VaccinationReminderController.update",
        "PUT /api/v2/vaccination_reminders/:id.?(json)?": "V2VaccinationReminderController.update",
        "DELETE /api/v2/vaccination_reminders/:id.?(json)?": "V2VaccinationReminderController.destroy",
        
        "GET /api/v2/videos/:id?.?(json)?": "V2VideoController.find",
        "GET /api/v2/videos/files/:type/:id": "V2VideoController.file",
        "POST /api/v2/videos(.json)?": "V2VideoController.create",
        "PATCH /api/v2/videos/:id.?(json)?": "V2VideoController.update",
        "PUT /api/v2/videos/:id.?(json)?": "V2VideoController.update",
        "DELETE /api/v2/videos/:id.?(json)?": "V2VideoController.destroy",
        
        "GET /api/v2/video_audit_loggings/:id?.?(json)?": "V2VideoAuditLoggingController.find",
        "GET /api/v2/video_audit_loggings/files/:type/:id": "V2VideoAuditLoggingController.file",
        "POST /api/v2/video_audit_loggings(.json)?": "V2VideoAuditLoggingController.create",
        "PATCH /api/v2/video_audit_loggings/:id.?(json)?": "V2VideoAuditLoggingController.update",
        "PUT /api/v2/video_audit_loggings/:id.?(json)?": "V2VideoAuditLoggingController.update",
        "DELETE /api/v2/video_audit_loggings/:id.?(json)?": "V2VideoAuditLoggingController.destroy",
        

        // Non RESTful API routes
        'POST /api/v2/push_notifications/push_notifications/channel/subscribe' : 'ChannelController.subscribe',
        'POST /api/v2/push_notifications/push_notifications/channel/unsubscribe' : 'ChannelController.unsubscribe',
        'GET /api/v2/push_notifications/device/:identifier/channels' : 'DeviceController.findDeviceChannels',

        // RESTful API routes, mostly used by the admin UI
        'GET /api/v2/push_notifications/apps' : 'AppController.find',
        'GET /api/v2/push_notifications/apps/:id' : 'AppController.find',
        'DELETE /api/v2/push_notifications/apps/:id' : 'AppController.destroy',
        'PUT /api/v2/push_notifications/apps/:id' : 'AppController.update',
        'POST /api/v2/push_notifications/apps/:id' : 'AppController.update',
        'POST /api/v2/push_notifications/apps' : 'AppController.create',

        'GET /api/v2/push_notifications/apps/:app_id/devices' : 'DeviceController.find',
        'GET /api/v2/push_notifications/apps/:app_id/devices/:id' : 'DeviceController.find',
        'DELETE /api/v2/push_notifications/apps/:app_id/devices/:id' : 'DeviceController.destroy',
        'POST /api/v2/push_notifications/apps/:app_id/devices' : 'DeviceController.create',
        'PUT /api/v2/push_notifications/apps/:app_id/devices' : 'DeviceController.update',
        'PUT /api/v2/push_notifications/apps/:app_id/devices/:id' : 'DeviceController.update',
        'GET /api/v2/push_notifications/apps/:app_id/devices/:id/channels' : 'DeviceController.findDeviceChannels',

        'GET /api/v2/push_notifications/apps/:app_id/channels' : 'ChannelController.find',
        'GET /api/v2/push_notifications/apps/:app_id/channels/:id' : 'ChannelController.find',
        'DELETE /api/v2/push_notifications/apps/:app_id/channels' : 'ChannelController.destroy',
        'DELETE /api/v2/push_notifications/apps/:app_id/channels/:id' : 'ChannelController.destroy',
        'POST /api/v2/push_notifications/apps/:app_id/channels' : 'ChannelController.create',
        'PUT /api/v2/push_notifications/apps/:app_id/channels' : 'ChannelController.update',
        'PUT /api/v2/push_notifications/apps/:app_id/channels/:id' : 'ChannelController.update',
        'POST /api/v2/push_notifications/apps/:app_id/channels/:id/subscribe' : 'ChannelController.subscribe',
        'POST /api/v2/push_notifications/apps/:app_id/channels/unsubscribe' : 'ChannelController.unsubscribe',

        'GET /api/v2/push_notifications/apps/:app_id/messages' : 'MessageController.find',
        'GET /api/v2/push_notifications/apps/:app_id/messages/:id' : 'MessageController.find',
        'GET /api/v2/push_notifications/channels/:channel_id/messages' : 'MessageController.findChannelMessages',
        // End Version 2

        // Begin Version Latest
        
        "GET /api/clinician_block_randomizers/:id?.?(json)?": "V2ClinicianBlockRandomizerController.find",
        "GET /api/clinician_block_randomizers/files/:type/:id": "V2ClinicianBlockRandomizerController.file",
        "POST /api/clinician_block_randomizers(.json)?": "V2ClinicianBlockRandomizerController.create",
        "PATCH /api/clinician_block_randomizers/:id.?(json)?": "V2ClinicianBlockRandomizerController.update",
        "PUT /api/clinician_block_randomizers/:id.?(json)?": "V2ClinicianBlockRandomizerController.update",
        "DELETE /api/clinician_block_randomizers/:id.?(json)?": "V2ClinicianBlockRandomizerController.destroy",
        
        "GET /api/clinician_codes/:id?.?(json)?": "V2ClinicianCodeController.find",
        "GET /api/clinician_codes/files/:type/:id": "V2ClinicianCodeController.file",
        "POST /api/clinician_codes(.json)?": "V2ClinicianCodeController.create",
        "PATCH /api/clinician_codes/:id.?(json)?": "V2ClinicianCodeController.update",
        "PUT /api/clinician_codes/:id.?(json)?": "V2ClinicianCodeController.update",
        "DELETE /api/clinician_codes/:id.?(json)?": "V2ClinicianCodeController.destroy",
        
        "GET /api/educations/:id?.?(json)?": "V2EducationController.find",
        "GET /api/educations/files/:type/:id": "V2EducationController.file",
        "POST /api/educations(.json)?": "V2EducationController.create",
        "PATCH /api/educations/:id.?(json)?": "V2EducationController.update",
        "PUT /api/educations/:id.?(json)?": "V2EducationController.update",
        "DELETE /api/educations/:id.?(json)?": "V2EducationController.destroy",
        
        "GET /api/healthcare_provider_contents/:id?.?(json)?": "V2HealthcareProviderContentController.find",
        "GET /api/healthcare_provider_contents/files/:type/:id": "V2HealthcareProviderContentController.file",
        "POST /api/healthcare_provider_contents(.json)?": "V2HealthcareProviderContentController.create",
        "PATCH /api/healthcare_provider_contents/:id.?(json)?": "V2HealthcareProviderContentController.update",
        "PUT /api/healthcare_provider_contents/:id.?(json)?": "V2HealthcareProviderContentController.update",
        "DELETE /api/healthcare_provider_contents/:id.?(json)?": "V2HealthcareProviderContentController.destroy",
        
        "GET /api/job_audit_loggings/:id?.?(json)?": "V2JobAuditLoggingController.find",
        "GET /api/job_audit_loggings/files/:type/:id": "V2JobAuditLoggingController.file",
        "POST /api/job_audit_loggings(.json)?": "V2JobAuditLoggingController.create",
        "PATCH /api/job_audit_loggings/:id.?(json)?": "V2JobAuditLoggingController.update",
        "PUT /api/job_audit_loggings/:id.?(json)?": "V2JobAuditLoggingController.update",
        "DELETE /api/job_audit_loggings/:id.?(json)?": "V2JobAuditLoggingController.destroy",
        
        "GET /api/question_categories/:id?.?(json)?": "V2QuestionCategoryController.find",
        "GET /api/question_categories/files/:type/:id": "V2QuestionCategoryController.file",
        "POST /api/question_categories(.json)?": "V2QuestionCategoryController.create",
        "PATCH /api/question_categories/:id.?(json)?": "V2QuestionCategoryController.update",
        "PUT /api/question_categories/:id.?(json)?": "V2QuestionCategoryController.update",
        "DELETE /api/question_categories/:id.?(json)?": "V2QuestionCategoryController.destroy",
        
        "GET /api/question_codes/:id?.?(json)?": "V2QuestionCodeController.find",
        "GET /api/question_codes/files/:type/:id": "V2QuestionCodeController.file",
        "POST /api/question_codes(.json)?": "V2QuestionCodeController.create",
        "PATCH /api/question_codes/:id.?(json)?": "V2QuestionCodeController.update",
        "PUT /api/question_codes/:id.?(json)?": "V2QuestionCodeController.update",
        "DELETE /api/question_codes/:id.?(json)?": "V2QuestionCodeController.destroy",
        
        "GET /api/question_types/:id?.?(json)?": "V2QuestionTypeController.find",
        "GET /api/question_types/files/:type/:id": "V2QuestionTypeController.file",
        "POST /api/question_types(.json)?": "V2QuestionTypeController.create",
        "PATCH /api/question_types/:id.?(json)?": "V2QuestionTypeController.update",
        "PUT /api/question_types/:id.?(json)?": "V2QuestionTypeController.update",
        "DELETE /api/question_types/:id.?(json)?": "V2QuestionTypeController.destroy",
        
        "GET /api/races/:id?.?(json)?": "V2RaceController.find",
        "GET /api/races/files/:type/:id": "V2RaceController.file",
        "POST /api/races(.json)?": "V2RaceController.create",
        "PATCH /api/races/:id.?(json)?": "V2RaceController.update",
        "PUT /api/races/:id.?(json)?": "V2RaceController.update",
        "DELETE /api/races/:id.?(json)?": "V2RaceController.destroy",
        
        "GET /api/search_audit_loggings/:id?.?(json)?": "V2SearchAuditLoggingController.find",
        "GET /api/search_audit_loggings/files/:type/:id": "V2SearchAuditLoggingController.file",
        "POST /api/search_audit_loggings(.json)?": "V2SearchAuditLoggingController.create",
        "PATCH /api/search_audit_loggings/:id.?(json)?": "V2SearchAuditLoggingController.update",
        "PUT /api/search_audit_loggings/:id.?(json)?": "V2SearchAuditLoggingController.update",
        "DELETE /api/search_audit_loggings/:id.?(json)?": "V2SearchAuditLoggingController.destroy",
        
        "GET /api/send_grids/:id?.?(json)?": "V2SendGridController.find",
        "GET /api/send_grids/files/:type/:id": "V2SendGridController.file",
        "POST /api/send_grids(.json)?": "V2SendGridController.create",
        "PATCH /api/send_grids/:id.?(json)?": "V2SendGridController.update",
        "PUT /api/send_grids/:id.?(json)?": "V2SendGridController.update",
        "DELETE /api/send_grids/:id.?(json)?": "V2SendGridController.destroy",
        
        "GET /api/settings/:id?.?(json)?": "V2SettingController.find",
        "GET /api/settings/files/:type/:id": "V2SettingController.file",
        "POST /api/settings(.json)?": "V2SettingController.create",
        "PATCH /api/settings/:id.?(json)?": "V2SettingController.update",
        "PUT /api/settings/:id.?(json)?": "V2SettingController.update",
        "DELETE /api/settings/:id.?(json)?": "V2SettingController.destroy",
        
        "GET /api/surveys/:id?.?(json)?": "V2SurveyController.find",
        "GET /api/surveys/files/:type/:id": "V2SurveyController.file",
        "POST /api/surveys(.json)?": "V2SurveyController.create",
        "PATCH /api/surveys/:id.?(json)?": "V2SurveyController.update",
        "PUT /api/surveys/:id.?(json)?": "V2SurveyController.update",
        "DELETE /api/surveys/:id.?(json)?": "V2SurveyController.destroy",
        
        "GET /api/survey_answers/:id?.?(json)?": "V2SurveyAnswerController.find",
        "GET /api/survey_answers/files/:type/:id": "V2SurveyAnswerController.file",
        "POST /api/survey_answers(.json)?": "V2SurveyAnswerController.create",
        "PATCH /api/survey_answers/:id.?(json)?": "V2SurveyAnswerController.update",
        "PUT /api/survey_answers/:id.?(json)?": "V2SurveyAnswerController.update",
        "DELETE /api/survey_answers/:id.?(json)?": "V2SurveyAnswerController.destroy",
        
        "GET /api/survey_questions/:id?.?(json)?": "V2SurveyQuestionController.find",
        "GET /api/survey_questions/files/:type/:id": "V2SurveyQuestionController.file",
        "POST /api/survey_questions(.json)?": "V2SurveyQuestionController.create",
        "PATCH /api/survey_questions/:id.?(json)?": "V2SurveyQuestionController.update",
        "PUT /api/survey_questions/:id.?(json)?": "V2SurveyQuestionController.update",
        "DELETE /api/survey_questions/:id.?(json)?": "V2SurveyQuestionController.destroy",
        
        "GET /api/survey_question_skip_logics/:id?.?(json)?": "V2SurveyQuestionSkipLogicController.find",
        "GET /api/survey_question_skip_logics/files/:type/:id": "V2SurveyQuestionSkipLogicController.file",
        "POST /api/survey_question_skip_logics(.json)?": "V2SurveyQuestionSkipLogicController.create",
        "PATCH /api/survey_question_skip_logics/:id.?(json)?": "V2SurveyQuestionSkipLogicController.update",
        "PUT /api/survey_question_skip_logics/:id.?(json)?": "V2SurveyQuestionSkipLogicController.update",
        "DELETE /api/survey_question_skip_logics/:id.?(json)?": "V2SurveyQuestionSkipLogicController.destroy",
        
        "GET /api/topics/:id?.?(json)?": "V2TopicController.find",
        "GET /api/topics/files/:type/:id": "V2TopicController.file",
        "POST /api/topics(.json)?": "V2TopicController.create",
        "PATCH /api/topics/:id.?(json)?": "V2TopicController.update",
        "PUT /api/topics/:id.?(json)?": "V2TopicController.update",
        "DELETE /api/topics/:id.?(json)?": "V2TopicController.destroy",
        
        "GET /api/twilios/:id?.?(json)?": "V2TwilioController.find",
        "GET /api/twilios/files/:type/:id": "V2TwilioController.file",
        "POST /api/twilios(.json)?": "V2TwilioController.create",
        "PATCH /api/twilios/:id.?(json)?": "V2TwilioController.update",
        "PUT /api/twilios/:id.?(json)?": "V2TwilioController.update",
        "DELETE /api/twilios/:id.?(json)?": "V2TwilioController.destroy",
        
        "GET /api/users/:id?.?(json)?": "V2UserController.find",
        "GET /api/users/files/:type/:id": "V2UserController.file",
        "POST /api/users(.json)?": "V2UserController.create",
        "PATCH /api/users/:id.?(json)?": "V2UserController.update",
        "PUT /api/users/:id.?(json)?": "V2UserController.update",
        "DELETE /api/users/:id.?(json)?": "V2UserController.destroy",
        
        "GET /api/user_audit_loggings/:id?.?(json)?": "V2UserAuditLoggingController.find",
        "GET /api/user_audit_loggings/files/:type/:id": "V2UserAuditLoggingController.file",
        "POST /api/user_audit_loggings(.json)?": "V2UserAuditLoggingController.create",
        "PATCH /api/user_audit_loggings/:id.?(json)?": "V2UserAuditLoggingController.update",
        "PUT /api/user_audit_loggings/:id.?(json)?": "V2UserAuditLoggingController.update",
        "DELETE /api/user_audit_loggings/:id.?(json)?": "V2UserAuditLoggingController.destroy",
        
        "GET /api/user_surveys/:id?.?(json)?": "V2UserSurveyController.find",
        "GET /api/user_surveys/files/:type/:id": "V2UserSurveyController.file",
        "POST /api/user_surveys(.json)?": "V2UserSurveyController.create",
        "PATCH /api/user_surveys/:id.?(json)?": "V2UserSurveyController.update",
        "PUT /api/user_surveys/:id.?(json)?": "V2UserSurveyController.update",
        "DELETE /api/user_surveys/:id.?(json)?": "V2UserSurveyController.destroy",
        
        "GET /api/user_survey_answers/:id?.?(json)?": "V2UserSurveyAnswerController.find",
        "GET /api/user_survey_answers/files/:type/:id": "V2UserSurveyAnswerController.file",
        "POST /api/user_survey_answers(.json)?": "V2UserSurveyAnswerController.create",
        "PATCH /api/user_survey_answers/:id.?(json)?": "V2UserSurveyAnswerController.update",
        "PUT /api/user_survey_answers/:id.?(json)?": "V2UserSurveyAnswerController.update",
        "DELETE /api/user_survey_answers/:id.?(json)?": "V2UserSurveyAnswerController.destroy",
        
        "GET /api/user_survey_videos/:id?.?(json)?": "V2UserSurveyVideoController.find",
        "GET /api/user_survey_videos/files/:type/:id": "V2UserSurveyVideoController.file",
        "POST /api/user_survey_videos(.json)?": "V2UserSurveyVideoController.create",
        "PATCH /api/user_survey_videos/:id.?(json)?": "V2UserSurveyVideoController.update",
        "PUT /api/user_survey_videos/:id.?(json)?": "V2UserSurveyVideoController.update",
        "DELETE /api/user_survey_videos/:id.?(json)?": "V2UserSurveyVideoController.destroy",
        
        "GET /api/vaccination_reminders/:id?.?(json)?": "V2VaccinationReminderController.find",
        "GET /api/vaccination_reminders/files/:type/:id": "V2VaccinationReminderController.file",
        "POST /api/vaccination_reminders(.json)?": "V2VaccinationReminderController.create",
        "PATCH /api/vaccination_reminders/:id.?(json)?": "V2VaccinationReminderController.update",
        "PUT /api/vaccination_reminders/:id.?(json)?": "V2VaccinationReminderController.update",
        "DELETE /api/vaccination_reminders/:id.?(json)?": "V2VaccinationReminderController.destroy",
        
        "GET /api/videos/:id?.?(json)?": "V2VideoController.find",
        "GET /api/videos/files/:type/:id": "V2VideoController.file",
        "POST /api/videos(.json)?": "V2VideoController.create",
        "PATCH /api/videos/:id.?(json)?": "V2VideoController.update",
        "PUT /api/videos/:id.?(json)?": "V2VideoController.update",
        "DELETE /api/videos/:id.?(json)?": "V2VideoController.destroy",
        
        "GET /api/video_audit_loggings/:id?.?(json)?": "V2VideoAuditLoggingController.find",
        "GET /api/video_audit_loggings/files/:type/:id": "V2VideoAuditLoggingController.file",
        "POST /api/video_audit_loggings(.json)?": "V2VideoAuditLoggingController.create",
        "PATCH /api/video_audit_loggings/:id.?(json)?": "V2VideoAuditLoggingController.update",
        "PUT /api/video_audit_loggings/:id.?(json)?": "V2VideoAuditLoggingController.update",
        "DELETE /api/video_audit_loggings/:id.?(json)?": "V2VideoAuditLoggingController.destroy",
        
        
        // End Version Latest

    };

    return routes;

}();
